package com.blog.backend.dao;

import com.blog.backend.entity.PostVisit;
import com.blog.backend.entity.PostVisitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * @author mengshuai
 * @since 2018.09.29
 */
public interface PostVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    int countByExample(PostVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    int deleteByExample(PostVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    int insert(PostVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    int insertSelective(PostVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    List<PostVisit> selectByExample(PostVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    PostVisit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") PostVisit record, @Param("example") PostVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    int updateByExample(@Param("record") PostVisit record, @Param("example") PostVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    int updateByPrimaryKeySelective(PostVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    int updateByPrimaryKey(PostVisit record);
}