package com.blog.backend.entity;

/**
 * @author mengshuai
 * @since 2018.09.29
 */
public class PostVisit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_visit.id
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_visit.post_id
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    private String postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_visit.visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    private Integer visit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_visit.id
     *
     * @return the value of post_visit.id
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_visit.id
     *
     * @param id the value for post_visit.id
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_visit.post_id
     *
     * @return the value of post_visit.post_id
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    public String getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_visit.post_id
     *
     * @param postId the value for post_visit.post_id
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    public void setPostId(String postId) {
        this.postId = postId == null ? null : postId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_visit.visit
     *
     * @return the value of post_visit.visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    public Integer getVisit() {
        return visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_visit.visit
     *
     * @param visit the value for post_visit.visit
     *
     * @mbggenerated Sat Sep 29 15:11:56 CST 2018
     */
    public void setVisit(Integer visit) {
        this.visit = visit;
    }
}